server:
  port: 8081
feign:
  okhttp:
    enabled: true   # 启用 OkHttp 客户端
hm:
  db:
    database: hm-item
  swagger:
    title: 黑马商城商品管理接口文档
    desc: "黑马商城商品管理接口文档"
    package: com.hmall.item.controller