server:
  port: 8085
feign:
  okhttp:
    enabled: true   # 启用 OkHttp 客户端
hm:
  db:
    database: hm-trade
  swagger:
    title: 黑马商城交易服务接口文档
    desc: "黑马商城交易服务接口文档"
    package: com.hmall.trade.controller