server:
  port: 8086
feign:
  okhttp:
    enabled: true   # 启用 OkHttp 客户端
hm:
  db:
    database: hm-pay
  swagger:
    title: 黑马商城支付服务接口文档
    desc: "黑马商城支付服务接口文档"
    package: com.hmall.pay.controller